name: leakage_detection
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - h5py
  - pytorch
  - torchvision
  - matplotlib
  - scikit-learn
  - scipy  # For statistical computations
  - cudatoolkit  # Automatically selects appropriate version for GPU if available
  - pip
  - pip:
      - argparse  # For command-line argument parsing
      - tqdm  # For progress bars
